# Collaboration Kit backend for clustering support
com.vaadin.experimental.collaborationEngineBackend=true
# Enable theme component style injection
com.vaadin.experimental.themeComponentStyles=true
# Tailwind CSS framework
com.vaadin.experimental.tailwindCss=true
# Hilla Full-stack Signals
com.vaadin.experimental.fullstackSignals=true
# Master Detail Layout component
com.vaadin.experimental.masterDetailLayoutComponent=true
# HorizontalLayout and VerticalLayout improvements
com.vaadin.experimental.layoutComponentImprovements=true
# Form Layout auto-responsive mode enabled by default
com.vaadin.experimental.defaultAutoResponsiveFormLayout=true
# Badge component
com.vaadin.experimental.badgeComponent=true
# MessageList Attachments
com.vaadin.experimental.messageListAttachments=true
# Slider component
com.vaadin.experimental.sliderComponent=true
# Modular Upload Components
com.vaadin.experimental.modularUpload=true
